// Package core contains the representation-independent Bloom filter math.
package core

import (
	"math"
	"math/bits"
)

// Parameters calculates a bit count and number of hash functions for the
// requested capacity and false-positive rate.
func Parameters(capacity uint64, falsePositiveRate float64) (bitCount, hashFunctions uint64, ok bool) {
	if capacity == 0 || !(falsePositiveRate > 0 && falsePositiveRate < 1) || math.IsNaN(falsePositiveRate) {
		return 0, 0, false
	}
	mFloat := math.Ceil(-float64(capacity) * math.Log(falsePositiveRate) / (math.Ln2 * math.Ln2))
	if math.IsNaN(mFloat) || math.IsInf(mFloat, 0) || mFloat >= math.Exp2(64) {
		return 0, 0, false
	}
	m := uint64(mFloat)
	kFloat := math.Round(float64(m) / float64(capacity) * math.Ln2)
	if math.IsNaN(kFloat) || math.IsInf(kFloat, 0) || kFloat >= math.Exp2(64) {
		return 0, 0, false
	}
	k := max(uint64(kFloat), 1)
	if m < 64 {
		m = 64
	}
	if m > math.MaxUint64-63 {
		return 0, 0, false
	}
	words := (m + 63) / 64
	if words > uint64(^uint(0)>>1) {
		return 0, 0, false
	}
	return words * 64, k, true
}

// Reduce maps hash uniformly into [0, n).
func Reduce(hash, n uint64) uint64 {
	hi, _ := bits.Mul64(hash, n)
	return hi
}

// Probe returns the i'th bit position generated by double hashing.
func Probe(h1, h2, i, bitCount uint64) uint64 {
	return Reduce(h1+i*h2, bitCount)
}
